### ISSUE TITLE
Random reboots when device goes into sleep

### ISSUE THREAD

**Issue by MaverickNextDoor** [itsHardStyl3r/G3_pie_issues#6]
This June build seems to have issues random rebooting (VS985) when device is about to sleep [few seconds after screen goes off, or when charger is unplugged (I've never known the phone to go into deep sleep when charging, so I assume it is normal to not deep sleep during charging)]. It only occurs when the screen is off. Here are 2 logs I got using SysLog apk (both logs where gotten immediately after random reboots completed.
[2019-07-21_21.41-Reboots.zip](https://github.com/itsHardStyl3r/G3_pie_issues/files/3427813/2019-07-21_21.41-Reboots.zip)
[2019-07-22_23.06.zip](https://github.com/itsHardStyl3r/G3_pie_issues/files/3427815/2019-07-22_23.06.zip)

**Comment by lipici** [comment]
had the same problem and after that the problem manifested even after clean wipe with previous build. now on stock, waiting for confirmation was resolved.

on pixel experience happens the same thing, aosp was ok but neither nougat, oreo, pie version never worked on my d855, sim not working.

**Comment by itsHardStyl3r** [comment]
I can't confirm this on 31/08 LineageOS 16.0 with OpenGApps Super and Magisk 19.3.

**Comment by MaverickNextDoor** [comment]
> I can't confirm this on 31/08 LineageOS 16.0 with OpenGApps Super and Magisk 19.3.

Sorry for the late update. My G3 (VS985) died on me days after reporting this issue: motherboard problems apparently. So this issue might have been motherboard related not ROM related.

**Comment by itsHardStyl3r** [comment]
Probably hardware related, feel free to comment.
